### ISSUE TITLE
Error: No such file: 'kitti_dbinfos_train.pkl'

### ISSUE THREAD

**Issue by xibaicai** [PointsCoder/VOTR#20]
**I didn't find this pkl file in your code, how should I get it please？？？**

Traceback (most recent call last):
  File "train.py", line 211, in <module>
    main()
  File "train.py", line 123, in main
    total_epochs=args.epochs
  File "/mnt/Disk8T/donght/VOTR/pcdet/datasets/__init__.py", line 48, in build_dataloader
    logger=logger,
  File "/mnt/Disk8T/donght/VOTR/pcdet/datasets/kitti/kitti_dataset.py", line 23, in __init__
    dataset_cfg=dataset_cfg, class_names=class_names, training=training, root_path=root_path, logger=logger
  File "/mnt/Disk8T/donght/VOTR/pcdet/datasets/dataset.py", line 32, in __init__
    ) if self.training else None
  File "/mnt/Disk8T/donght/VOTR/pcdet/datasets/augmentor/data_augmentor.py", line 21, in __init__
    cur_augmentor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "/mnt/Disk8T/donght/VOTR/pcdet/datasets/augmentor/data_augmentor.py", line 29, in gt_sampling
    logger=self.logger
  File "/mnt/Disk8T/donght/VOTR/pcdet/datasets/augmentor/database_sampler.py", line 19, in __init__
    with open(str(db_info_path), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/Disk8T/donght/VOTR/data/kitti/kitti_dbinfos_train.pkl'

**Comment by rogercomeon** [comment]
l couldn't get it. How do you solve it?

**Comment by hyungyu-Park** [comment]
So do I.. 😄 
Is there anybody solved this issue?

**Comment by bueeciel9** [comment]
First, generate train.pkl file with openpcdet.  Then, copy and paste them in the VOTR pcdet folder.

https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md
